export const REQUEST_TASKS = 'REQUEST_TASKS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const ERROR_RECEIVE_TASKS = 'ERROR_RECEIVE_TASKS';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const DELETE_TASK = 'DELETE_TASKS';
export const ERROR_DELETE_TASK= 'ERROR_DELETE_TASKS';
